version: '3.9'
services:
  account_db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_DB: 'account-manager'
      POSTGRES_USER: 'weinber'
      POSTGRES_PASSWORD: 'weinber'
    ports:
      - 5432:5432
    expose:
      - '5432'
    volumes:
      - account:/var/lib/postgresql/data
volumes:
  account: